### ISSUE TITLE
remount question

### ISSUE THREAD

**Issue by sinAshish** [sfu-mial/labtools#1]
> remotemount.sh
Suppose you have access (with SSH) to a cluster, and you want to browse selected files from a large dataset, edit a few files, etc. In this case sync/copy tools are overkill, you can instead mount the remote files so they appear to your local machine as if they are a local folder:

@bencardoen 
Can we mount our lab machines as well to our personal?
say if I want to mount my Mac to mial35 and mial41, or a combinatorial of this, is it possible to do this via this script?

**Comment by bencardoen** [comment]
@sinAshish Ideally I'd rewrite it accepting arguments (instead of hardcoding in the script). 
You can do multiple mounts (mac -> 35, mac -> 41), you would just need to run the script multiple times (and use different mount points). 
Not sure if this answers your use case?

**Comment by sinAshish** [comment]
got it, i will try this @bencardoen

**Comment by bencardoen** [comment]
@sinAshish see updated readme + script, changes:
- accepts args (no hardcoded vars)
- it should work on Mac, but I can't test that
- you can ask it to unmount
- you can N-1 mounting (but you cannot share a mountpoint afaic).
Happy to accept PRs if you have changes/fixes
